### ISSUE TITLE
Terra Incognita encountered an error during the registries_event phase

### ISSUE THREAD

**Issue by Mysteriaa** [Azmalent/terra-incognita#10]
Occurs upon starting Minecraft 1.16.5. I'm using 1.4.1.1.
Crashlog: https://pastebin.com/rPG961At
Latest.log: https://pastebin.com/buAhkXm5

**Comment by Azmalent** [comment]
Terra Incognita 1.4.X is not compatible with Cuneiform 1.2 as I changed some code there. You need to upgrade to 1.5 or downgrade Cuneiform to 1.1.
