### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Azmalent/terra-incognita#13]
`Minecraft v1.16.5`
`Forge v36.0.13`
`Terra Incognita v1.5`

_Cough_ Another server crash. _Cough_
[Crash Report](https://gist.github.com/WenXin20/635a91c3a12f718374217bd1f7da265c)

**Comment by Azmalent** [comment]
Try 1.5.1, it should be fixed.

**Comment by WenXin20** [comment]
Thanks!
