### ISSUE TITLE
Crash when changing configs

### ISSUE THREAD

**Issue by dr3ams** [Azmalent/terra-incognita#17]
Mainly the [Trees] section(didn't tried anything else)

[Trees]
	#Default: true
	"Apple Trees Enabled" = **false**
	#Default: true
	"Disable Apple Drop From Oaks" = **false**

Changing to false resulting in crash:

[crash-2021-02-12_12.20.46-fml.txt](https://github.com/Azmalent/terra-incognita/files/5971020/crash-2021-02-12_12.20.46-fml.txt)

Tested only with Terra Incognita installed.

**Comment by Azmalent** [comment]
This issue is fixed in 1.5.2.
