### ISSUE TITLE
Crash When Disabling Swamp Flowers

### ISSUE THREAD

**Issue by FrogBirdd** [Azmalent/terra-incognita#19]
Title is self explanatory, disabling swamp flowers in the config causes a crash.
[crash-2021-02-13_15.50.21-fml.txt](https://github.com/Azmalent/terra-incognita/files/5976521/crash-2021-02-13_15.50.21-fml.txt)

**Comment by Azmalent** [comment]
This bug is now fixed in 1.5.3.
