### ISSUE TITLE
[Sorry]Crash Server Start 1.16.4 again

### ISSUE THREAD

**Issue by SugarDaddii** [Azmalent/terra-incognita#22]
i dont know if the mistake is on my side but i cant start your mod because i get this crash log

https://pastebin.com/FSUYR3rJ

(Maybe its cuneiform)

**Comment by Azmalent** [comment]
Please try 1.5.3.2.

**Comment by Azmalent** [comment]
Assuming this bug was succesfully fixed in 1.5.3.2.
