### ISSUE TITLE
Failed To Synchronize Registry Data From Server In Minecraft

### ISSUE THREAD

**Issue by pjlasl** [Azmalent/terra-incognita#24]
I am seeing something interesting with the latest version. I load it on my server and everything seems to be good.
I load it in my client and when I connect to my server I get the following message: Failed To Synchronize Registry Data From Server In Minecraft.

Nothing gets written to the log so I don't have anything there, just the message on the client side every time I try to connect. Removing your mod, I am able to connect to my server.

**Comment by Azmalent** [comment]
That's weird. Are you sure you had the same version on client?

**Comment by pjlasl** [comment]
yh, everything matches...i started a fresh install of my server to check...

**Comment by Azmalent** [comment]
Did you delete the config too?

**Comment by Azmalent** [comment]
Try the 1.6 beta, blocks and items are now registered regardless of configs, so this should solve your issue.

**Comment by Azmalent** [comment]
Assuming to be fixed in 1.6+
