### ISSUE TITLE
Failed to load datapacks, can't proceed with server load

### ISSUE THREAD

**Issue by xAlicatt** [Azmalent/terra-incognita#26]
Here's the log: https://paste.ee/p/PQdJ6

TI version 1.6
Forge ver 36.0.46

I don't see any other mod referenced in the error, but this did start after updating some of the other mods in my pack and updating Forge.

**Comment by Azmalent** [comment]
I just published the release version, it should fix the crash. 
It seems like a problem with certain biome(s), they will now be logged, so please send me the logs either way.

**Comment by xAlicatt** [comment]
Was able to load with the new release. 

Here's the logs for that: https://paste.ee/p/qelA1

**Comment by xAlicatt** [comment]
Seems like when I saved the new version from the Curse site, it overwrote the beta version since it had the same file name and confused the Curse app and it deleted it totally. I will try reinstalling.

**Comment by xAlicatt** [comment]
TI definitely installed this time...it shows up in the mod menu. I was able to load into my world this time :)

Log: https://paste.ee/p/jz21f

**Comment by Azmalent** [comment]
Nice, thanks!
