### ISSUE TITLE
Terra Incognita Failed to load correctly

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Azmalent/terra-incognita#27]
Tried every version of the mod known to man and nothing seems to be working I'm on forge 36.0.42

Screenshot of error message
![Crash](https://i.imgur.com/e2LB3kW.png)

Crash Report
[crash-2021-03-10_16.54.45-fml.txt](https://github.com/Azmalent/terra-incognita/files/6117574/crash-2021-03-10_16.54.45-fml.txt)

**Comment by Azmalent** [comment]
You need to update TI to 1.6 or downgrade Cuneiform to 1.2.

**Comment by Azmalent** [comment]
Then you need to upgrade to the release version which just came out.
I don't recall removing what the beta version depended on but whatever, 1.2.1 is required for the release version and will work with it.

**Comment by SirOMGitsYOU** [comment]
Just tried the latest one off curseforge 

[crash-2021-03-10_18.19.05-client.txt](https://github.com/Azmalent/terra-incognita/files/6118199/crash-2021-03-10_18.19.05-client.txt)

**Comment by Azmalent** [comment]
This crash is caused by Tetra, at least take a look at the log before reporting.
