### ISSUE TITLE
Crash upon right clicking a basket in world

### ISSUE THREAD

**Issue by Alexander3847575** [Azmalent/terra-incognita#3]
We've experienced this a couple times now, but when you place a basket and rclick, it crashes the dedicated server. Likely a compat issue.

Steps to reproduce:
 - Place basket
 - Right click on basket
  
https://hatebin.com/qugvquvlip

**Comment by Azmalent** [comment]
Okay, I fixed it. The problem was that it tried to fetch the translated display name on the server side.
Until 1.4 comes out, if you want to use placed baskets on a server, you can rename them on an anvil as a workaround.
