### ISSUE TITLE
Butterflies seem to be causing a crash.

### ISSUE THREAD

**Issue by SirChamomile** [Azmalent/terra-incognita#30]
crash-report - [crash-2021-03-12_19.46.19-server.txt](https://github.com/Azmalent/terra-incognita/files/6133945/crash-2021-03-12_19.46.19-server.txt)

It's taking down the server, so I've disabled the butterfly spawning for the time being.

**Comment by Azmalent** [comment]
Apparently there's a flow in butterfly AI which causes them to land on empty blocks, I'll try to figure it out for the 1.6.1 version.
You can safely disable butterflies, they can spawn and despawn freely like bats in vanilla.

**Comment by nosevole** [comment]
I've been having the same issue, but for some reason the config file will not save changes. Apologies if this isn't a bug but something I'm doing wrong, however I'm stumped!

**Comment by Azmalent** [comment]
> I've been having the same issue, but for some reason the config file will not save changes. Apologies if this isn't a bug but something I'm doing wrong, however I'm stumped!

That's weird, try to delete the config so that it refreshes. It works fine for me. Might be because of the quirks in Forge's config system, it prints a lot of errors in the console saying that invalid keys were corrected, even when the file is already correct.

**Comment by nosevole** [comment]
Thanks for the suggestion, unfortunately it didn't work for me and the config still reverts and crashes the game. If it's working for others then I'm pretty sure it's a problem my end, so I'll just be patient and wait for the butterfly fix :) Thanks again! x

**Comment by Azmalent** [comment]
The 1.6.1 has been released, it should fix the issue! Don't forget to update Cuneiform too, and I highly recommend Chocolate Fix because there are new biomes.
I wasn't able to figure out why the butterflies were landing on empty shapes in the first place, but I did add the necessary checks to prevent the crashes.

**Comment by Azmalent** [comment]
Assuming this to be fixed.

**Comment by SirChamomile** [comment]
Yes! Thanks for the terrific work Azmalent. It's a lovely mod, and the butterflies are back and are very charming.

**Comment by Azmalent** [comment]
Glad you like it :)
