### ISSUE TITLE
[Issue and Suggestion] Biomes

### ISSUE THREAD

**Issue by Matthysse** [Azmalent/terra-incognita#32]
Hello!
When loading Terra Incognita with Terraforged, the Tundra biome spawns really weirdly, and the borders because of the snow are visible:
![2021-03-17_16 52 42](https://user-images.githubusercontent.com/32510957/111501193-0ddccf00-8745-11eb-8306-0f41e8901310.png)
And with the Snow Under Trees mod, spruce trees spawn with snow underthem, even if the biome doesn't have snow.

I don't use Biomes O Plenty anymore, because Abnormal's mods are better and Biomes O Plenty now only creates duplicate of those better biomes. But I miss one specific biome from Biomes O Plenty, which I loved in ExtraBiomes XL, it's the coniferous forest, with fir trees:
![ExtrabiomesXL](https://user-images.githubusercontent.com/32510957/111501926-ac693000-8745-11eb-8275-f72127719899.jpg)
It would be awesome if you could add this biome, with a snowy and normal variant, with majestic and tall trees.

**Comment by Azmalent** [comment]
The snow problems are probably related to how I register the tundra, I'll look into how other mods handle similar biomes. 
As far as the conifer forest goes, it's a good biome indeed, I might do something similar with larches when I add them.

**Comment by Matthysse** [comment]
Oh nice !! I love larches from our Mountains here in France ! Can't wait to see them. Thanks for looking into the issue!

**Comment by Azmalent** [comment]
Please try 1.6.3, the issue with snow under trees should be fixed (and possibly the Terraforged issue too, I haven't tested it)

**Comment by Matthysse** [comment]
Mmmh tried to find Tundras in Terraforged, and they seem not to generate anymore, I tested a lot of worlds with Natures's Compass to locate the biome, but I can't find any.

**Comment by Azmalent** [comment]
It's been a while but the 2.0 release now features the Boreal Forest biome, which is fairly similar to the Coniferous Forest :)
