### ISSUE TITLE
[Simply Tea integration] Drinking the last serving of fireweed tea doesn't give you your teacup back

### ISSUE THREAD

**Issue by Febilian** [Azmalent/terra-incognita#35]
Title.

`Minecraft 1.16.5`
`Forge 36.1.4`
`terraincognita-1.16.3-1.6.4.1`
`cuneiform-1.16.3-1.2.4`
`Simply Tea! 2.3.4 for 1.16.x`

**Comment by Azmalent** [comment]
Fixed in 1.7 beta.
