### ISSUE TITLE
Forge 36.1.10+ Incompatiblity

### ISSUE THREAD

**Issue by WenXin20** [Azmalent/terra-incognita#36]
`Minecraft v1.16.5`
`Forge v36.1.13`
`Terra Incognita v-1.6.4.1`

After updating my Forge version to v36.1.13, the game will no longer launch due to a breaking Forge change at 
MinecraftForge/MinecraftForge#7696.

![2021-04-26_21 54 04](https://user-images.githubusercontent.com/12000593/116178358-0a8d1980-a6db-11eb-8c9a-2b624400fb4b.png)

**Comment by Corvus20** [comment]
I am getting the same problem in Forge v36.1.16

**Comment by Sunconure11** [comment]
Same issue here.

**Comment by Azmalent** [comment]
Fixed in the new update.
