### ISSUE TITLE
[Suggestion] Make the caribou moss "snow-loggable" via compatibility with the "Snow - Real Magic!" mod

### ISSUE THREAD

**Issue by Corvus20** [Azmalent/terra-incognita#37]
I usually end up disabling the caribou moss because of how it makes the terrain of biomes it generates in sort of "splotchy", for a lack of a better term. "Snow - Real Magic!" has a feature that allows snow to be placed on plants, fences, etc., and still have them poke out through the snow. Last I checked some modded plants worked with it, so its definitely possible.

**Comment by Azmalent** [comment]
Implemented in 1.7 beta!
