### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Azmalent/terra-incognita#4]
`Minecraft v1.16.5`
`Forge v36.0.13`
`Terra Incognita v1.4`

The wood types causes a server crash when loaded.
[Crash Report](https://gist.github.com/WenXin20/a7c30b24b9cbc47697672a9a02418647)

**Comment by Azmalent** [comment]
Sorry about that.
Fixed in the new hotfix

**Comment by WenXin20** [comment]
Thanks!
