### ISSUE TITLE
[Issue] Flower basket client crash with Quark installed

### ISSUE THREAD

**Issue by Febilian** [Azmalent/terra-incognita#40]
Explanation of behavior: I left-clicked a plant item(in this case, I tried both a brown mushroom and a piece of coral) in my inventory while a flower basket was also in my inventory; the client immediately crashes.

I also recently updated Quark, which has a [changelog](https://www.curseforge.com/minecraft/mc-mods/quark/files/3326040) mentioning a fix to the inventory drop-in behavior with shulker boxes; maybe something changed that also happened to break your integration code?

Mod versions:

`cuneiform-1.16.3-1.2.5`
`terraincognita-1.16.3-1.7`
`AutoRegLib-1.6-49`
`Quark-r2.4-312`

Crash log: https://gist.github.com/Febilian/2497d4847fca8119838f5e881cf7e8c2

**Comment by Explode007** [comment]
I don't know if this one is specifically with quark, but I am crashing when picking it up from the creative inventory.

Here is the crashlog: 
[crash-2021-06-16_00.18.05-client.txt](https://github.com/Azmalent/terra-incognita/files/6660263/crash-2021-06-16_00.18.05-client.txt)

**Comment by erisdev** [comment]
The `IDropInItem` interface changed. Two of the methods take an additional parameter now. It's an easy fix, at least...

https://github.com/Vazkii/AutoRegLib/commit/7f6192796e2eb455788bed160d345820062ddcab?branch=7f6192796e2eb455788bed160d345820062ddcab&diff=split#diff-7b4a03c411f63aa87436eb04c7dec0750230a87be9ad0d69747b3220eebb3440R16

**Comment by toErIpNid** [comment]
Any eta on when this will get fixed? I was wanting to play with terra incognita alongside quark but I still can't use the basket.

**Comment by Azmalent** [comment]
Sorry that it's taking so long, I'm currently busy with some IRL things and a bit stuck on the code.
I've already fixed this issue and will try to finish the 1.6 release soon!

**Comment by Azmalent** [comment]
Fixed in the new beta!
