### ISSUE TITLE
Snow & Ice generates odd when tundra and any snowy biomes are next to each other.

### ISSUE THREAD

**Issue by Thombias** [Azmalent/terra-incognita#41]
Something i've noticed for quite a while:
If a tundra generates and it happens to be next to any vanilla snow biome (snow plains for example) the snow and ice is generating in an odd chunky way. I don't really know how to describe it in a better way but i think these 2 images explain exactly what i mean:
![2021-07-10_22 47 35](https://user-images.githubusercontent.com/46842890/125176203-eddc8a00-e1d1-11eb-8321-7e1d1f9d009d.png)
![2021-07-10_22 47 49](https://user-images.githubusercontent.com/46842890/125176204-ef0db700-e1d1-11eb-9cbf-cf71c6a64fa9.png)
Now i'm not sure if this is happening because of the many mods i have installed, but i'm pretty sure they're not at fault here as i don't have a single mod installed that changes the way biomes or terrain are generating. I only have mods installed that add biomes and change some vegetation here and there. (Like flowers, some trees, etc.)
Though if you really need a mod list, i can provide one just in case:
![Modlist](https://user-images.githubusercontent.com/46842890/125176274-82df8300-e1d2-11eb-9d4f-902be7a72256.PNG)
The ice generating in this chunky way is only visible in the 2nd picture. (the world map)

**Comment by Azmalent** [comment]
Hey, sorry for the late reply.
IIRC the borders weren't so ugly last time I checked in my testing instance. It's possible that one of your mods modifies the snow feature, making it more squarish. For one, Snow! Real Magic does this thing, but it's configurable. So could you search your mod configs for 'snow'? 

If you're on Linux or Mac, you can use `grep` to search text in multiple files. I use Linux myself, so not sure how to do this on Windows.
