### ISSUE TITLE
[Simply Tea Integration] Fireweed Tea not compatible with tea sweetening

### ISSUE THREAD

**Issue by a-soulspark** [Azmalent/terra-incognita#42]
Hi, I'm the developer of the [Tea Kettle](https://www.curseforge.com/minecraft/mc-mods/tea-kettle) mod, which is similar to Simply Tea, but with a more immersive and hands-on approach. It even has compatibility with Simply Tea, so their tea can be brewed with my mod's mechanics!

#### The Issue
Recently, someone submitted a-soulspark/TeaKettle#15 relating how Fireweed Tea couldn't be brewed with Tea Kettle, so I fixed it. The problem is, you still couldn't _sweeten_ Fireweed Tea without a recipe.
#### The *Real* Issue
The problem is, although I could add the recipe myself and thus _craft_ the sweetened cup, it would grant no bonus effects: the tea's level remained the same.
#### The Solution 
Didn't manage to clone your repository, so here's a possible fix: when adding Fireweed Tea [here](../blob/c9e12df9669f03dfbe5943735ffab18cbd502265/src/main/java/azmalent/terraincognita/common/integration/SimplyTeaIntegration.java#L31), use a TeaDrink instead of Food.
It checks if tea is sweetened, and boosts the tea's effects if so. I'm not sure if that would cause any trouble, might want to ask KnightMiner about it.
For it to be craftable, [here's](https://gist.github.com/a-soulspark/f1285b40d0e314dd882a5bc0eae550ac) the recipe I used, a `simplytea:shapeless_honey`-type recipe. Just drop it into your `recipes` folder and you're done! Thanks for your time 😄

**Comment by Azmalent** [comment]
Thanks for the help, I've added sweetening support in the new beta.
Nice mod btw :)

**Comment by a-soulspark** [comment]
Your timing was spot-on, as I was about to release an update as well '^-^
Thanks once again, and thanks for making this mod!
