### ISSUE TITLE
Fast Graphics Setting: Hazel/Apple Texture

### ISSUE THREAD

**Issue by OmnipotentSeth** [Azmalent/terra-incognita#43]
Fantastic mod. 

But I removed apple and hazel items from my modpack because the apple and hazel trees look bad when the graphic settings are set to "fast". 

Though it looks good when the settings are "fancy".

**Comment by Azmalent** [comment]
Unfortunately, this is impossible to fix since there is no way to customize the fast textures. This was possible in older versions, but now they're generated automatically, and it doesn't work well with unusual block models.
