### ISSUE TITLE
interacting with the Cupboard Inventory is Crashing the Game

### ISSUE THREAD

**Issue by Morabert** [Azmalent/terra-incognita#44]
[crash-2021-07-23_19.25.57-client.txt](https://github.com/Azmalent/terra-incognita/files/6870318/crash-2021-07-23_19.25.57-client.txt)

**Comment by Morabert** [comment]
It did it again, this time with a chest
[crash-2021-07-23_19.42.32-client.txt](https://github.com/Azmalent/terra-incognita/files/6870392/crash-2021-07-23_19.42.32-client.txt)

**Comment by Morabert** [comment]
It seems it may in fact crashing when interacting with either be Apple Chests, or Baskets, or Both:
The game crashed whilst rendering screen
Error: java.lang.AbstractMethodError: Method azmalent/terraincognita/common/integration/quark/BasketDropIn.canDropItemIn(Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;Lnet/minecraft/inventory/container/Slot;)Z is abstract
Exit Code: -1
[debug.log](https://github.com/Azmalent/terra-incognita/files/6872406/debug.log)

**Comment by Azmalent** [comment]
Duplicate of #40, this bug was fixed in the new beta.
