### ISSUE TITLE
[1.16] Dispenser no longer shears sheep

### ISSUE THREAD

**Issue by Bricktricker** [Azmalent/terra-incognita#45]
terraincognita: 1.16.3-1.7
cuneiform: 1.16.3-1.2.5

Put a sheep in front of a dispenser and fill the dispenser with shears. Then trigger the dispenser with a redstone signal. In vanilla Minecraft this would shear the sheep and drop some wool, but with cuneiform and terraincognita installed nothing happens.

**Comment by Azmalent** [comment]
Fixed in the new beta!
