### ISSUE TITLE
Bug: Apple Tree saplings make plant pots invisible.

### ISSUE THREAD

**Issue by Tsunamori74** [Azmalent/terra-incognita#48]
I need to test this with other plants from the mod, but whenever I put an apple sapling in a pot, the sapling goes in as intended but the pot becomes invisible. This doesn’t happen with modded plant containers such as the planters or flower boxes from Supplementaries.

Just for reference, I am using optifine G8 and Complementary shaders, but this doesn’t look like a shader issue in my opinion.

**Comment by Tsunamori74** [comment]
Update: I tested it and yes, it’s just the apple tree sapling that behaves this way.

**Comment by Azmalent** [comment]
Fixed in the release version!
