### ISSUE TITLE
Common_setup crash

### ISSUE THREAD

**Issue by Matthysse** [Azmalent/terra-incognita#5]
Hello!
I have your mod in a pretty large modpack, and I always have this crash when loading the game with the new update of your mod :
https://pastebin.com/cdh19BZD

I know common_setups crashs appear randomly and are fixed when rebooting the game, in this case it doesn't work, and it's always the same error.

**Comment by Azmalent** [comment]
That's strange. I've never encountered that before.
Apparently I'll have to come up with a hack to fix this, I'll do some googling and fix this ASAP.

**Comment by Matthysse** [comment]
Nice, thanks! Love your mod it adds so much atmosphere to the world!

**Comment by Azmalent** [comment]
Thanks for the feedback :)
Please try the new hotfix version. This one should work.

**Comment by Matthysse** [comment]
I now works thanks!
