### ISSUE TITLE
Disabled Flora still spawns when bonemeal is used on grass

### ISSUE THREAD

**Issue by Freshah** [Azmalent/terra-incognita#51]
terraincognita-1.16.3-1.7-BETA2.jar

So far I've only confirmed it with Primroses but I have below set in the config;

	#Adds wild garlic, primroses and foxgloves to forests. These flowers can also be found in flower forests.
	#Default: true
	"Forest Flowers Enabled" = false

but bonemeal still brings those flowers.  for now I've blockswapped them but a bug is a bug.

**Comment by Azmalent** [comment]
Fixed in the release version!
