### ISSUE TITLE
cannot remove items from basket

### ISSUE THREAD

**Issue by AppeaseTheBees** [Azmalent/terra-incognita#53]
Both cuneiform and TI are fully updated.

I can collect items just fine, and can even use the quark feature of right clicking items into the basket when basket is not in my off-hand passively collecting forage drops. If I hover over the basket in my inventory, I can see all the items stored. 
The problem arises when I place the basket on the ground to remove the items inside it. 
Left click breaks it as normal, but right clicking it only gives me a super quick flash of the inventory/basket inventory screen, and sometimes it doesn't even do anything when i right click. this makes it impossible to remove items from the basket.
I have removed all other mods I play with to test it, along with resource packs as well, and it still has that problem, so its not a mod conflict. 
this is for 1.16.5 (forge 36.2.0)

**Comment by Azmalent** [comment]
Fixed in the new version!
