### ISSUE TITLE
Dedicated server crashes on startup when trying to run Terraincognita 

### ISSUE THREAD

**Issue by NJL5390** [Azmalent/terra-incognita#59]
Terraincognita version: 2.0 - BETA 4
Cuneiform version: 1.3.3
Terrablender version: 1.1.0.101
Minecraft Version: 1.18.2
Forge Version: 40.1.51

Hi,
I tried testing the latest version of this mod on my modded server and found that the server just crashes on startup whenever I try and run Terraincognita on the server.

Here is what is shown when it crashes: 
![2022-06-24](https://user-images.githubusercontent.com/64381954/175621805-4f38a84a-fb89-4d5e-af11-199b43644efb.png)

No crash report is generated when this crash occurs and nothing is included in the server logs about it either, which is why I haven't included them and only included this screenshot. Let me know if you need me to do any testing in relation to this issue and I will happy to help out however I can.

Thanks.

**Comment by Azmalent** [comment]
Try Cuneiform 1.3.3.1, it should fix the issue!

**Comment by NJL5390** [comment]
It has indeed! Thanks for the quick fix and I look forward to seeing what you add to this mod in the future!
