### ISSUE TITLE
Missing Textures for Larch and Ginko

### ISSUE THREAD

**Issue by SirChamomile** [Azmalent/terra-incognita#61]
Larch and Ginko textures seem to be missing. Could be on my end, I'll check in depth tomorrow.

![image](https://user-images.githubusercontent.com/23204608/175857898-72e9325a-d4b8-4697-bc37-2610eea124bb.png)

**Comment by Azmalent** [comment]
These are WIP content and they don't generate in the world yet anyway. The missing textures are one of the things I need to do before release.

**Comment by Azmalent** [comment]
Fixed in the release version!
