### ISSUE TITLE
[1.18.2] Crash on startup (Crash report not generated, Mixin issue?)

### ISSUE THREAD

**Issue by aking4125** [Azmalent/terra-incognita#62]
Hello, Upon startup. The game crashes but no crash report is created. Below is the older log file after disabling batches of mods and localizing to just this one. I dunno.

Any Ideas?

[2022-06-27-1.log](https://github.com/Azmalent/terra-incognita/files/8992472/2022-06-27-1.log)

**Comment by Azmalent** [comment]
The log says it's from Adorn, this has nothing to do with my mod.
