### ISSUE TITLE
Crash when launching with Botania

### ISSUE THREAD

**Issue by aoxiangtianji** [Azmalent/terra-incognita#63]
*I'm not good at English, so I use translation software.

As title.
Install only Botania, Terra Incognita and their dependencies.

Minecraft log: https://mclo.gs/Uq7jche

HMCL log: https://mclo.gs/QnaOIEL

**Comment by tlitookilakin** [comment]
this seems to happen whenever terra incognita is loaded with _any_ mod that has _any_ entity mixin of any kind. Which is a lot of them.
