### ISSUE TITLE
Flowering Grass using wrong color pallet

### ISSUE THREAD

**Issue by Reshy** [Azmalent/terra-incognita#65]
![2022-07-26_22 27 26](https://user-images.githubusercontent.com/2096384/181168269-b6203e8d-631a-4007-9143-02b43263d18b.png)

**Comment by Azmalent** [comment]
Pretty sure this is caused by Quark's "Greener grass" feature. You need to add flowering grass to the config, and then it will be the same color.

**Comment by Reshy** [comment]
Ah, let me go to that then, thanks regardless!
