### ISSUE TITLE
Crash with visual work bench

### ISSUE THREAD

**Issue by LordCys** [Azmalent/terra-incognita#66]
I'm having 2 issues and I will post them separately. This issue has a crash I can report back with.

When using visual workbench with this mod it immediately crashes when crafting on a workbench, in this instance I created an oak pressure plate and the game immediately crashed on trying to take the item out of the workbench.

Crash report: https://pastebin.com/tAseLDDp

latest.log: https://pastebin.com/LdtHgGty

Mods I'm using: 
![image_2022-07-30_142310136](https://user-images.githubusercontent.com/72561595/181936600-a5ff54bc-fece-4eec-ab08-ada43c9b0162.png)

**Comment by Azmalent** [comment]
Looks like I messed up the suspicious stew somehow, for now you can disable fern fiddleheads to fix the issue.

**Comment by Azmalent** [comment]
Please try Cuneiform 1.3.4, it should fix the issue!
