### ISSUE TITLE
Terra Incognita breaks Sophisticated backpack

### ISSUE THREAD

**Issue by LordCys** [Azmalent/terra-incognita#67]
Unfortunately I have no crash report to add to this error.

When using Terra Incognita with Sophisticated backpacks everything works normally until you add a crafting upgrade to the backpack then suddenly the backpack becomes unusable. It becomes impossible to open with both it's default key (B) and with holding and left clicking. You can place the bag normally but you still can't open it even on the ground.

Edit: I will also have issues of crafting eating leftover items at times and editing recipes. Such as trying to turn a blue orchid into blue dye will instead create suspicious stew.

![image_2022-07-30_143927018](https://user-images.githubusercontent.com/72561595/181937147-8286c1be-e89c-4a6c-8eb2-b422355a79ef.png)

Again, my mod list:

![image_2022-07-30_143300677](https://user-images.githubusercontent.com/72561595/181936919-2fdbb633-e887-4dc4-938e-2bc63145b743.png)

Curseforge profile options: 
![image](https://user-images.githubusercontent.com/72561595/181936886-e57a7fac-5cd9-4699-b9b2-56b4090b7cd3.png)

When removing terra incognita backpacks and recipes work as intended.

**Comment by Azmalent** [comment]
Pretty sure this is related to the other issue you opened, the suspicious stew recipes are broken.
As for the backpacks, I think it tries to process my broken recipe, can you post the logs please?

**Comment by LordCys** [comment]
> Pretty sure this is related to the other issue you opened, the suspicious stew recipes are broken. As for the backpacks, I think it tries to process my broken recipe, can you post the logs please?

> Pretty sure this is related to the other issue you opened, the suspicious stew recipes are broken. As for the backpacks, I think it tries to process my broken recipe, can you post the logs please?

Sure! Sorry about the wait and sorry I didn't post the log. I assumed the logs were the same as crash logs, I've never actually reported an issue before.

https://pastebin.com/8rxiBN3y

Thank you for looking at this and thank you for your hard work on this mod. It's one of my favorites and I appreciate it. I hope this log helps, if you need anything else from me just let me know and I'll do my best to help!

**Comment by Azmalent** [comment]
Thanks for the kind words :)
After checking the logs it seems like the same issue as #66, so I'm closing this one as a duplicate.
For now you can disable fern fiddleheads in the config, it should disable the broken recipes.
