### ISSUE TITLE
Magenta/ Purple Dye Recipe issue

### ISSUE THREAD

**Issue by OverEarth12** [Azmalent/terra-incognita#69]
With this mod installed, some flower from vanilla, this mod and other mods which give purple or magenta (May be also some other dyes) will give suspicious stew instead. I tried to fix this with CraftTweaker, but it's didn't work
Purple Primrose from this mod
![2022-10-14_22 54 25](https://user-images.githubusercontent.com/56574543/195890180-92627174-224a-4422-a5a1-023e6b050681.png)
Allium
![2022-10-14_22 53 34](https://user-images.githubusercontent.com/56574543/195890272-cdb7be7f-b389-471f-9d26-0cc48aa954a1.png)
and others (more than this, these're just some of them)
![2022-10-14_22 54 28](https://user-images.githubusercontent.com/56574543/195890597-483283d7-7ea7-46eb-ba3a-5874e9185d1e.png)
![2022-10-14_22 53 42](https://user-images.githubusercontent.com/56574543/195890650-d7405b89-6dff-468f-9bde-0a78572bee88.png)

**Comment by Azmalent** [comment]
It's a known issue with the suspicious stew recipe, you can disable fern fiddleheads in the config to fix this for now.
I've been busy lately, but I want to finish the release version soon, just need to draw a couple more textures and I'll be ready to fix all the bugs.

**Comment by Azmalent** [comment]
Please try Cuneiform 1.3.4, it should fix the issue!
