### ISSUE TITLE
[Crash] Crash when typing the letter "t" into the search bar

### ISSUE THREAD

**Issue by Catomax262** [Azmalent/terra-incognita#71]
Report: https://crashy.net/RNPc3MrBeGWmp7r5JvUL

**Comment by Azmalent** [comment]
The recipes for suspicious stew with fern fiddleheads are currently broken, you can fix it by disabling fiddleheads in the config for now.

**Comment by Azmalent** [comment]
Please try Cuneiform 1.3.4, it should fix the issue!
