### ISSUE TITLE
butterflies mourning_cloak type have missing texture and still can spawn in the world

### ISSUE THREAD

**Issue by OverEarth12** [Azmalent/terra-incognita#73]
![2023-01-12_15 53 21](https://user-images.githubusercontent.com/56574543/212021853-ed200b8e-b7e5-43da-bf60-708307e803f7.png)
most spawn at meadow biome
1.18.2
terraincognita-1.18.2-2.0
cuneiform-1.18.2-1.3.3.1
TerraBlender-forge-1.18.2-1.2.0.126
log:
[latest.log](https://github.com/Azmalent/terra-incognita/files/10399810/latest.log)
no other mods than nbt viewer (IBE Editor) and jei mods

**Comment by Azmalent** [comment]
Oops, I thought they didn't spawn in the beta.
The texture is already done, it will come with the full release (I just need to take some time to fix all the remaining bugs and stuff)

**Comment by Azmalent** [comment]
Fixed in the release version!
